config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :products do
    resources :auctions, only: [ :create ] do
      resources :bids, only: [ :create  ]
    end
    member do
      put :transfer
    end
  end

root 'products#index'

end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :product
  has_many :bids #ovako smo implementirali bids messege u Auctionu
  # ovako radi jer smo relaciju vec definisali sa strane Bid-a: tamo gde pise da Bid belongs to user i auction
  
  
  def top_bid
    bids.order(value: :desc).first
    # moramo implementirati bids message u auction, i to radimo gore
  end
  
  def current_bid
    top_bid.nil? ? value : top_bid.value
    # ako je value nil, idemo na inicijalnu vrednost, ako nije, idemo na top vrednost
  end
  
  def ended?
    ends_at < Time.now
    # atribut je samo ends_at bez znaka pitanja
  end
end

app/models/bid.rb
class Bid < ActiveRecord::Base
  belongs_to :user
  belongs_to :auction
  
  validates_numericality_of :value
end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :user
    has_one :auction # ovime smo dobili pristup auction metodu dole
    
    def has_auction?
        auction.present?
        # u tom smislu, sa recju "auction" idemo do relationshipa
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :authenticate_user! # ovaj metod mi daje devise
end

app/controllers/auctions_controller.rb
class AuctionsController < ApplicationController
    def create
        product = Product.find params[:product_id]
        auction = Auction.new auction_params.merge! product_id: product.id
        if auction.save
            redirect_to product, notice: "Product was put to auction"
        else
            redirect_to product, alert: "Something went wrong"
        end
    end
    
    def auction_params
    params.require(:auction).permit(:value, :ends_at)
    # tek sad radi strftime metod na aukciji, jer smo pre ovoga taj metod pozivali na Nil klasu
    # i sad moram kroz konzolu da dodajem za proizvod 2 tu vrednost, jer sam je kreiirao pre ovoga
    # Auction.all
    # Auction.find(2).update_attribute(:ends_at, Time.now(2015, 5, 10, 21, 00)
    # svakako smo posle zamenili i taj metod, ali je update bio neophodan
    end
end

app/controllers/bids_controller.rb
require "place_bid"

class BidsController < ApplicationController

    def create
        service = PlaceBid.new bid_params
    
        if service.execute
        redirect_to product_path(params[:product_id]), notice: "Bid je uspesno postavljen"
        else
        redirect_to product_path(params[:product_id]), alert: "Nesto je poslo naopacke!"
        end
    end
    
    def bid_params
        params.require(:bid).permit(:value).merge!(
            user_id: current_user.id,
            auction_id: params[:auction_id]
            )
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params.merge! user_id: current_user.id)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def transfer
    
      product = Product.find params[:id] # ovaj :id imamo u params hashu
      
      if product.auction.ended? # da ne bi moglo da se posalje veci bid nakon zavrsetka aukcije
           product.update_attribute :user_id, product.auction.top_bid.user_id # lep nacin da dodjemo do id-a pobednika
           redirect_to product, notice: "Uspesno je preneto vlasnistvo nad proizvodom"
      else
            redirect_to product, alert: "Aukcija jos nije zavrsena!"
      end
      
     
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
    .container-fluid
        .navbar-header
            %button.navbar-toggle.collapsed{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                %span.sr-only Toggle navigation
                %span.icon-bar
                %span.icon-bar
                %span.icon-bar
            =link_to "Auctions", root_path, class: "navbar-brand"
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
            %ul.nav.navbar-nav
                %li
                    =link_to "Products", products_path
            
            %ul.nav.navbar-nav.navbar-right
                -if current_user
                    %p.navbar-text
                        Ulogovani ste kao #{current_user.email}
                        =link_to "Sign out", destroy_user_session_path, method: :delete
                -else
                    %li=link_to "Sign in", new_user_session_path

app/views/auctions/_status.html.haml
-if @product.auction.top_bid.user_id == current_user.id
    %p Pobedio si na aukciji!
    %p
        =link_to "Claim this product", transfer_product_path(@product), class: "btn btn-primary", method: :put
        -# bez put metoda nemamo route za ovaj zahtev
-else
    %p Izgubio si na aukciji

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Auctions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "nav" %>
    
    <div class ="container">
     
    <%= content_tag :div, alert, class: "flash bg-danger" if alert %>
    <%= content_tag :div, notice, class: "flash bg-success" if notice %>
     
    <%= yield %>   
    
  </div>


</body>
</html>

app/views/products/_auction.html.haml
-unless @product.has_auction?
    %h2 Put this product to auction
    
    =form_for [@product, Auction.new] do |f|
        %p
            =f.text_field :value
        
        %p
            =f.datetime_select :ends_at
            =f.button class: "btn btn-primary"

app/views/products/_bid.html.haml
-unless @product.has_auction? == false
    -if @product.auction.ended?
        = render "auctions/status"
        
    -else
        =form_for [@product, @product.auction, Bid.new] do |f|
            %p.message
                %strong
                    -if @product.auction.top_bid.present?
                        -if @product.auction.top_bid.user_id == current_user.id
                            Current bid:
                        -else
                            You were outbid:
                            -# ovime se top_bid metod relatuje na auction a ne na product sto i ima smisla
                    -else
                        Current bid:
                        
                    =@product.auction.current_bid
            %p
                Ends at: #{l(@product.auction.ends_at, format: :short)}
            
            %p
                =f.text_field :value 
                -# ovaj value se odnosi na bid, ne na auction
                =f.button class: "btn btn-primary"
-# znaci ovo se ucitava na kraju stranice

:javascript    
    $(function(){
        var user_id = "#{current_user.id}";
        var auction_id = "#{@product.auction.id}";
        var form = $("#new_bid");
        
        var auctionSocket = new AuctionSocket(
                user_id,
                auction_id,
                form
            );
        }
    );

app/views/products/_form.html.haml
= form_for @product do |f|
  - if @product.errors.any?
    #error_explanation
      %h2= "#{pluralize(@product.errors.count, "error")} prohibited this product from being saved:"
      %ul
        - @product.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :image
    = f.text_field :image
  .actions
    = f.submit 'Save'

app/views/products/edit.html.haml
%h1 Editing product

= render 'form'

= link_to 'Show', @product
\|
= link_to 'Back', products_path

app/views/products/index.html.haml
%h1 Listing products

.row
    %ul.list-unstyled
        - @products.each do |product|
            %li.col-md-3
                %h2= link_to product.name, product
                %p 
                    =link_to product do
                        =image_tag product.image, height: 200
                %p
                    =link_to 'Edit', edit_product_path(product)
                    |
                    =link_to 'Destroy', product, :method => :delete, :data => {:confirm => 'Are you sure?'}
          
.row
    %p
        =link_to 'New Product', new_product_path, class: "btn btn-primary"

app/views/products/new.html.haml
%h1 New product

= render 'form'

= link_to 'Back', products_path

app/views/products/show.html.haml
%h1= @product.name

%p
    = image_tag @product.image

%p
    = link_to 'Edit', edit_product_path(@product)
    \|
    = link_to 'Back', products_path

= render "auction"
= render "bid"

:javascript
    App = {
        websocket_url: "wss://#{request.host}:#{request.port}/"
    };
-# morao sam dodati s inace mi je javljao gresku da ne moze da ostvari unsecured connection, na sajt do koga je dosao preko secured connectionna, tj. preko https-auction
-# njemu to nije pokazivao verovatno jer je radio na localhostu